# Generated by Django 5.1.1 on 2024-10-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LibMS", "0007_bookhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="is_first_login",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="password",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="username",
        ),
    ]
