# Generated by Django 5.1.1 on 2024-10-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LibMS", "0008_remove_faculty_is_first_login_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="phone",
            field=models.CharField(
                default="null", max_length=10, verbose_name="Phone Number"
            ),
        ),
    ]
