# Generated by Django 5.1.1 on 2025-02-02 09:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LibMS", "0009_faculty_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookissue",
            name="iissue_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
