# Generated by Django 5.1.1 on 2025-02-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LibMS", "0010_bookissue_iissue_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookissue",
            name="iissue_id",
        ),
    ]
