# Generated by Django 5.1.1 on 2025-02-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LibMS", "0012_bookissue_issue_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookissue",
            name="issue_id",
        ),
    ]
